# Generated by Django 4.0.2 on 2022-02-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
