# Generated by Django 4.0.2 on 2022-02-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_rename_username_customer_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
    ]
