# Generated by Django 4.0.2 on 2022-02-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_rename_username_field_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
