# Generated by Django 4.0.2 on 2022-02-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_remove_customer_date_created_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
